# Generated by Django 4.2.7 on 2023-12-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoprestamo',
            name='monto_maximo',
        ),
    ]
