# Generated by Django 4.2.7 on 2023-12-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('prestamos', '0002_remove_tipoprestamo_monto_maximo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
