# Generated by Django 4.2.7 on 2023-12-05 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_alter_solicitudprestamo_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprestamo',
            name='tipo_prestamo',
            field=models.ForeignKey(db_column='loan_type', on_delete=django.db.models.deletion.CASCADE, to='prestamos.tipoprestamo'),
        ),
    ]
